name: Publish Test Reports
on:
  workflow_run:
    workflows: ['Check Linux Packages'] # runs after Check Linux Packages worflow
    types:
      - completed
jobs:
  report:
    permissions:
      contents: read
      actions: read
      checks: write
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
      with:
        artifact: test-results            # artifact name
        name: JUnit Test Report           # Name of the check run which will be created
        path: '**/build/test-results/**/TEST-*.xml' # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
        fail-on-empty: false
